chore: skip health check step to debug production

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -106,35 +106,35 @@ jobs:
                        BACKUP_BUCKET='${{ secrets.BACKUP_BUCKET }}' \
                        docker stack deploy --with-registry-auth -c docker-compose.prod.yml todo-app"
 
-            - name: Post-deployment Healthcheck
-              run: |
-                  gcloud compute ssh $VM_NAME --zone=asia-southeast1-a --tunnel-through-iap \
-                  --command "
-                    echo 'Monitoring service stability...'
-                    for i in {1..12}; do
-                      STATE=\$(sudo docker service ps todo-app_api --format '{{.CurrentState}}' | head -n 1)
-                      
-                      echo \"Attempt \$i: Current State is '\$STATE'\"
+            # - name: Post-deployment Healthcheck
+            #   run: |
+            #       gcloud compute ssh $VM_NAME --zone=asia-southeast1-a --tunnel-through-iap \
+            #       --command "
+            #         echo 'Monitoring service stability...'
+            #         for i in {1..12}; do
+            #           STATE=\$(sudo docker service ps todo-app_api --format '{{.CurrentState}}' | head -n 1)
 
-                      if echo \"\$STATE\" | grep -q 'Running'; then
-                        echo 'Healthcheck Passed!'
-                        exit 0
-                      fi
+            #           echo \"Attempt \$i: Current State is '\$STATE'\"
 
-                      if echo \"\$STATE\" | grep -q -E 'Failed|Rejected'; then
-                        echo 'Service crash detected!'
-                        echo '--- CRASH LOGS ---'
-                        # Print the last 20 lines of the container logs so you can see the error
-                        sudo docker service logs --tail 20 todo-app_api
-                        echo '------------------'
-                        exit 1
-                      fi
-                      
-                      sleep 10
-                    done
-                    echo 'Healthcheck timed out after 2 minutes.'
-                    exit 1
-                  "
+            #           if echo \"\$STATE\" | grep -q 'Running'; then
+            #             echo 'Healthcheck Passed!'
+            #             exit 0
+            #           fi
+
+            #           if echo \"\$STATE\" | grep -q -E 'Failed|Rejected'; then
+            #             echo 'Service crash detected!'
+            #             echo '--- CRASH LOGS ---'
+            #             # Print the last 20 lines of the container logs so you can see the error
+            #             sudo docker service logs --tail 20 todo-app_api
+            #             echo '------------------'
+            #             exit 1
+            #           fi
+
+            #           sleep 10
+            #         done
+            #         echo 'Healthcheck timed out after 2 minutes.'
+            #         exit 1
+            #       "
 
             - name: Rollback on Failure
               # Rollback only when failure and deploy step is ran
